spin_manifest_version = 2

[application]
name = "spin-animal-facts"
version = "0.1.0"
description = "A simple demonstration of using component dependencies"

[[trigger.http]]
route = "/..."
component = "spin-animal-facts"

[component.spin-animal-facts]
source = "target/wasm32-wasi/release/animal_facts_app.wasm"
allowed_outbound_hosts = [
     "https://random-data-api.fermyon.app",
]
# Uncomment the following line to enable configuration inheritance
# dependencies_inherit_configuration = true
[component.spin-animal-facts.build]
command = "cargo build --manifest-path animal-facts-app/Cargo.toml --target wasm32-wasi --release"
[component.spin-animal-facts.dependencies]
"component:animal-facts/animal-facts" = { path = "target/wasm32-wasi/release/animal_facts_dep.wasm" }